---
extends: default

rules:
  line-length:
    max: 200
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false

ignore:
  - _site/
  - build/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .asset_pipeline*
  - node_modules
  - vendor/*
